server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}
  producer:
    group: xiechimon-shan-link_stats-save_producer-group
    send-message-timeout: 3000

shan-link:
  domain:
    default: 127.0.0.1:8000
  group:
    max-num: 20

shanlink:
  stats:
    default-province: "北京"
    default-city: "北京"
