spring:
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config-prod.yaml
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876

shan-link:
  domain:
    default: ${DOMAIN:localhost}
