brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# Docker 内部网络下使用容器名，客户端通过同一网络可解析
brokerIP1 = rmqbroker
autoCreateTopicEnable = false
