server:
  port: 8001

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      username: root

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: shan-link_stats-save_producer-group
    send-message-timeout: 3000

shan-link:
  domain:
    default: 127.0.0.1:8001